CPG-DEV/src/objects/Business__c.object
<CustomObject>
    <fields>
        <fullName>BusinessUnitAlias__c</fullName>
        <globalPicklist>CargillBusinessAlias</globalPicklist>
        <label>Business Alias</label>
        <required>true</required>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>CargillEnterprise__c</fullName>
        <globalPicklist>Cargill_Enterprise</globalPicklist>
        <label>Cargill Enterprise</label>
        <required>true</required>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>CargillGroup__c</fullName>
        <globalPicklist>Cargill_Group</globalPicklist>
        <label>Cargill Group</label>
        <required>true</required>
        <type>Picklist</type>
    </fields>
    <label>Business</label>
    <nameField>
        <label>Business Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

CPG-DEV/src/objects/User.object
<CustomObject>
    <fields>
        <fullName>CargillEnterprise__c</fullName>
        <globalPicklist>Cargill_Enterprise</globalPicklist>
        <label>Cargill Enterprise</label>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>CargillGroup__c</fullName>
        <globalPicklist>Cargill_Group</globalPicklist>
        <label>Cargill Group</label>
        <type>Picklist</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

CPG-DEV/src/classes/TaskTriggerHelper_Test.cls
@isTest
public class TaskTriggerHelper_Test {
    static testMethod void validateHelper(){
        Business__c b = new Business__c();
        b.BusinessUnitAlias__c = 'Foods Brazil';
        b.Name = 'Cargill Foods Brazil';
        b.CargillEnterprise__c = 'FoodIngredientsBioIndustrialFIBI';
        b.CargillGroup__c = 'GoToMarket (GTM)';
        Insert b;
        
        
        Task insertNew = new Task();
        insertNew.Subject ='Test';
        insertNew.OwnerId = [select Id from User  Limit 1].ID;
        insertNew.Priority = 'Normal';
        insertNew.Status ='Open';
        Insert insertNew;
    }

}